const sqlite3 = require("sqlite3").verbose();

const db = new sqlite3.Database("./orders.db");

const items = [
  // cold_dish
  [
    "盐味包菜",
    "塩キャベツ",
    "Salted Cabbage",
    600,
    "cold_dish",
    "cold_salted_cabbage.png",
  ],
  ["毛豆", "枝豆", "Edamame", 400, "cold_dish", "cold_edamame.png"],
  [
    "拌鸡胗",
    "砂肝和え",
    "Marinated Chicken Gizzard",
    600,
    "cold_dish",
    "cold_marinated_chicken_gizzard.png",
  ],
  [
    "烧鸡(整只)",
    "鶏の丸焼き(一羽)",
    "Red Cooked Chicken (Whole)",
    1200,
    "cold_dish",
    "cold_red_cooked_chicken.png",
  ],
  [
    "烧鸡(半只)",
    "鶏の丸焼き(半羽)",
    "Red Cooked Chicken (Half)",
    600,
    "cold_dish",
    "cold_red_cooked_chicken.png",
  ],
  ["辣白菜", "キムチ", "Kimchi", 400, "cold_dish", "cold_kimchi.png"],
  [
    "皮蛋豆腐",
    "ピータン豆腐",
    "Century Egg Tofu",
    600,
    "cold_dish",
    "cold_century_egg_tofu.png",
  ],
  [
    "拌木耳",
    "キクラゲ和え",
    "Black Fungus Salad",
    500,
    "cold_dish",
    "cold_black_fungus_salad.png",
  ],
  [
    "酱牛腱",
    "牛スネ醤油煮",
    "Soy-braised Beef Shank",
    1000,
    "cold_dish",
    "cold_soy_braised_beef_shank.png",
  ],
  [
    "拌牛肚",
    "ハチノス和え",
    "Marinated Beef Tripe",
    800,
    "cold_dish",
    "cold_marinated_beef_tripe.png",
  ],
  [
    "拌牛肉",
    "牛肉和え",
    "Marinated Beef",
    1000,
    "cold_dish",
    "cold_marinated_beef.png",
  ],
  [
    "炸花生米",
    "揚げピーナッツ",
    "Fried Peanuts",
    400,
    "cold_dish",
    "cold_fried_peanuts.png",
  ],
  [
    "拌豆干丝",
    "干し豆腐和え",
    "Shredded Dried Tofu Salad",
    550,
    "cold_dish",
    "cold_shredded_dried_tofu_salad.png",
  ],
  ["春卷", "春巻き", "Spring Rolls", 400, "cold_dish", "cold_spring_rolls.png"],
  [
    "酱猪蹄",
    "豚足",
    "Soy-braised Pig Trotters",
    300,
    "cold_dish",
    "cold_soy_braised_pig_trotters.png",
  ],
  [
    "拌猪蹄",
    "豚足和え",
    "Marinated Pork Feet",
    600,
    "cold_dish",
    "cold_marinated_pork_feet.png",
  ],
  [
    "拌猪耳",
    "豚ミミ和え",
    "Marinated Pork Ear",
    600,
    "cold_dish",
    "cold_marinated_pork_ear.png",
  ],
  [
    "炸薯条",
    "ポテトフライ",
    "French Fries",
    500,
    "cold_dish",
    "cold_french_fries.png",
  ],
  [
    "台湾香肠",
    "台湾腸詰め",
    "Taiwan Sausage",
    300,
    "cold_dish",
    "cold_taiwan_sausage.png",
  ],
  [
    "日式鸡蛋卷",
    "玉子焼き",
    "Japanese Rolled Omelette",
    500,
    "cold_dish",
    "cold_japanese_rolled_omelette.png",
  ],
  [
    "酱鸡爪",
    "鶏もみじ",
    "Soy-braised Chicken Feet",
    800,
    "cold_dish",
    "cold_soy_braised_chicken_feet.png",
  ],
  [
    "拌脱骨鸡爪",
    "骨なし鶏もみじ和え",
    "Marinated Boneless Chicken Feet",
    800,
    "cold_dish",
    "cold_marinated_boneless_chicken_feet.png",
  ],
  [
    "蒜泥白肉",
    "豚肉のニンニクソースかけ",
    "Sichuan Garlic Pork Slices",
    600,
    "cold_dish",
    "cold_sichuan_garlic_pork_slices.png",
  ],

  // street_food
  [
    "肉夹馍",
    "中華風ハンバーガー",
    "Chinese hamburger",
    500,
    "dim_sum_rice",
    "street_chinese_hamburger.png",
  ],
  ["豆浆", "豆乳", "Soy Milk", 200, "dim_sum_rice", "street_soy_milk.png"],
  ["豆腐脑", "トウファオ", "Douhua", 300, "dim_sum_rice", "street_douhua.png"],
  [
    "凉皮",
    "リャンピー",
    "Liangpi Cold Noodles",
    800,
    "dim_sum_rice",
    "street_liangpi.png",
  ],
  [
    "烤冷面",
    "冷麺焼き",
    "Grilled Northeastern Cold Noodles",
    500,
    "dim_sum_rice",
    "street_grilled_northeastern_cold_noodles.png",
  ],
  [
    "馅饼",
    "シェンビン",
    "Meat Pie",
    400,
    "dim_sum_rice",
    "street_meat_pie.png",
  ],
  [
    "芝麻球",
    "ゴマ団子",
    "Fried Sesame Balls",
    500,
    "dim_sum_rice",
    "street_fried_sesame_balls.png",
  ],
  [
    "韩式冷面",
    "韓国冷麺",
    "Korean Cold Noodles",
    800,
    "dim_sum_rice",
    "street_korean_cold_noodles.png",
  ],
  [
    "日式炒面",
    "焼きそば",
    "Yakisoba",
    800,
    "dim_sum_rice",
    "street_yakisoba.png",
  ],
  [
    "茶叶蛋",
    "お茶漬け玉子",
    "Chinese Tea Egg",
    150,
    "dim_sum_rice",
    "street_chinese_tea_egg.png",
  ],
  [
    "羊杂汤",
    "羊モツスープ",
    "Lamb Offal Soup",
    1000,
    "dim_sum_rice",
    "street_lamb_offal_soup.png",
  ],
  [
    "牛肉汤",
    "牛肉スープ",
    "Beef Soup",
    1000,
    "dim_sum_rice",
    "street_beef_soup.png",
  ],
  [
    "皮蛋粥",
    "ピータンお粥",
    "Century Egg Congee",
    700,
    "dim_sum_rice",
    "street_century_egg_congee.png",
  ],

  // dim_sum_rice
  [
    "卤肉饭",
    "ル一ロ一飯",
    "Braised pork on rice",
    800,
    "dim_sum_rice",
    "dim_braised_pork_on_rice.png",
  ],
  [
    "生煎小笼包",
    "焼き小籠包",
    "Pan-fried soup dumplings",
    500,
    "dim_sum_rice",
    "dim_pan_fried_soup_dumplings.png",
  ],
  ["水饺", "水餃子", "Dumplings", 800, "dim_sum_rice", "dim_dumplings.png"],
  [
    "煎饺",
    "焼き餃子",
    "Potstickers",
    600,
    "dim_sum_rice",
    "dim_potstickers.png",
  ],
  [
    "韭菜盒子",
    "ニラのおやき",
    "Fried Chinese Leek Dumplings",
    500,
    "dim_sum_rice",
    "dim_fried_chinese_leek_dumplings.png",
  ],
  [
    "酸汤水饺",
    "酸っぱいスープ水餃子",
    "Hot and Sour Dumpling Soup",
    800,
    "dim_sum_rice",
    "dim_hot_sour_dumpling_soup.png",
  ],
  ["馄饨", "ワンタン", "Wonton", 600, "dim_sum_rice", "dim_wonton.png"],
  [
    "拌馄饨",
    "ワンタン和え",
    "Marinated Wonton",
    800,
    "dim_sum_rice",
    "dim_marinated_wonton.png",
  ],
  [
    "葱油饼",
    "ツォンションヨピン",
    "Scallion Pancake",
    300,
    "dim_sum_rice",
    "dim_scallion_pancake.png",
  ],
  [
    "手抓饼",
    "シューシャオピン",
    "Chinese Flaky Pancake",
    500,
    "dim_sum_rice",
    "dim_chinese_flaky_pancake.png",
  ],
  [
    "牛肉炒饭",
    "牛肉チャーハン",
    "Beef Fried Rice",
    800,
    "dim_sum_rice",
    "dim_beef_fried_rice.png",
  ],
  [
    "鸡排饭",
    "鶏カツ飯",
    "Crispy Chicken Chop Rice",
    800,
    "dim_sum_rice",
    "dim_crispy_chicken_chop_rice.png",
  ],
  [
    "麻婆豆腐盖饭",
    "麻婆丼",
    "Mapo Tofu with Rice",
    800,
    "dim_sum_rice",
    "dim_mapo_tofu_rice.png",
  ],
  [
    "炒饭",
    "チャーハン",
    "Fried Rice",
    800,
    "dim_sum_rice",
    "dim_fried_rice.png",
  ],
  ["米饭", "ライス", "Plain Rice", 200, "dim_sum_rice", null],

  // grilled_fried
  [
    "烤牡蛎",
    "焼き力キ",
    "Grilled Oyster",
    1000,
    "grilled_fried",
    "grilled_oyster.png",
  ],
  [
    "炸臭豆腐(黑)",
    "揚げ臭い豆腐(黒)",
    "Deep-Fried Black Stinky Tofu (Black)",
    800,
    "grilled_fried",
    "grilled_stinky_tofu_black.png",
  ],
  [
    "炸臭豆腐(白)",
    "揚げ臭い豆腐(白)",
    "Deep-Fried Black Stinky Tofu (White)",
    800,
    "grilled_fried",
    "grilled_stinky_tofu_white.png",
  ],
  [
    "羊肉串",
    "ラム肉串焼き",
    "Grilled Lamb",
    200,
    "grilled_fried",
    "grilled_lamb_skewer.png",
  ],
  [
    "烤猪蹄",
    "焼き豚足",
    "Grilled Pork Feet",
    500,
    "grilled_fried",
    "grilled_pork_feet.png",
  ],
  [
    "烤大虾",
    "焼き大海老",
    "Grilled Prawn",
    200,
    "grilled_fried",
    "grilled_prawn_skewer.png",
  ],
  [
    "鸡肉串",
    "鶏肉串焼き",
    "Grilled Chicken Thigh",
    150,
    "grilled_fried",
    "grilled_chicken_thigh_skewer.png",
  ],
  [
    "鸡皮串",
    "鶏皮串焼き",
    "Grilled Chicken Skin",
    150,
    "grilled_fried",
    "grilled_chicken_skin_skewer.png",
  ],
  [
    "砂肝串",
    "砂肝串焼き",
    "Grilled Chicken Gizzard",
    150,
    "grilled_fried",
    "grilled_chicken_gizzard_skewer.png",
  ],
  [
    "鱿鱼串",
    "イカ串焼き",
    "Grilled Squid Skewers",
    200,
    "grilled_fried",
    "grilled_squid_skewer.png",
  ],
  [
    "烤面筋",
    "面筋串焼き",
    "Grilled Gluten",
    300,
    "grilled_fried",
    "grilled_gluten_skewer.png",
  ],
  [
    "烤实蛋",
    "シータン串焼き",
    "Grilled Solid Egg",
    300,
    "grilled_fried",
    "grilled_seitan_egg_skewer.png",
  ],
  [
    "炸香肠",
    "ソーセージ揚げ",
    "Fried Sausage",
    500,
    "grilled_fried",
    "fried_sausage.png",
  ],
  [
    "炸大虾",
    "海老唐揚げ",
    "Fried Prawn",
    600,
    "grilled_fried",
    "fried_prawn.png",
  ],
  [
    "炸鸡块",
    "鶏の唐揚げ",
    "Fried Chicken",
    600,
    "grilled_fried",
    "fried_chicken.png",
  ],
  [
    "炸鱿鱼须",
    "イカゲソ唐揚げ",
    "Fried Squid Legs",
    650,
    "grilled_fried",
    "fried_squid_legs.png",
  ],

  // casserole
  [
    "毛血旺",
    "毛血旺",
    "Chongqing style boiled Blood Curd",
    1000,
    "casserole",
    "casserole_spicy_blood_curd.png",
  ],
  [
    "砂锅小龙虾",
    "ザリガニ鍋",
    "Crayfish Casserole",
    1000,
    "casserole",
    "casserole_crayfish.png",
  ],
  [
    "砂锅鸭血",
    "鴨の血鍋",
    "Duck Blood Jelly Casserole",
    1000,
    "casserole",
    "casserole_duck_blood_jelly.png",
  ],
  [
    "砂锅鸡肉",
    "鶏肉鍋",
    "Chicken Casserole",
    1000,
    "casserole",
    "casserole_chicken.png",
  ],
  [
    "砂锅牡蛎",
    "カキ鍋",
    "Oyster Casserole",
    1200,
    "casserole",
    "casserole_oyster.png",
  ],
  [
    "砂锅肥肠",
    "ホルモン鍋",
    "Large Intestines Casserole",
    1000,
    "casserole",
    "casserole_large_intestines.png",
  ],
  [
    "砂锅豆腐",
    "豆腐鍋",
    "Tofu Casserole",
    800,
    "casserole",
    "casserole_tofu.png",
  ],
  [
    "砂锅牛肚",
    "ハチノス鍋",
    "Honeycomb Tripe Casserole",
    1000,
    "casserole",
    "casserole_honeycomb_tripe.png",
  ],
  [
    "砂锅排骨",
    "パイコツ鍋",
    "Pork Ribs Casserole",
    1000,
    "casserole",
    "casserole_pork_ribs.png",
  ],
  [
    "砂锅红烧肉",
    "豚角煮鍋",
    "Braised Pork Belly Casserole",
    1000,
    "casserole",
    "casserole_braised_pork_belly.png",
  ],
  [
    "砂锅牛肉",
    "牛肉鍋",
    "Beef Casserole",
    1000,
    "casserole",
    "casserole_beef.png",
  ],
  [
    "砂锅蛤蜊",
    "アサリ鍋",
    "Clams Casserole",
    800,
    "casserole",
    "casserole_clams.png",
  ],
  [
    "砂锅猪蹄",
    "豚足鍋",
    "Pork Feet Casserole",
    800,
    "casserole",
    "casserole_pork_feet.png",
  ],
  [
    "砂锅粉丝",
    "春雨鍋",
    "Vermicelli Casserole",
    800,
    "casserole",
    "casserole_vermicelli.png",
  ],
  [
    "砂锅大虾",
    "大海老鍋",
    "Prawn Casserole",
    1200,
    "casserole",
    "casserole_prawn.png",
  ],
  [
    "砂锅鸡爪",
    "もみじ鍋",
    "Chicken Feet Casserole",
    1000,
    "casserole",
    "casserole_chicken_feet.png",
  ],
  [
    "砂锅牛筋",
    "牛足すじ鍋",
    "Beef Tendon Casserole",
    1000,
    "casserole",
    "casserole_beef_tendon.png",
  ],
  [
    "砂锅金针菇",
    "エノキ鍋",
    "Enoki Casserole",
    800,
    "casserole",
    "casserole_enoki.png",
  ],
  [
    "砂锅牛肉金针菇",
    "牛肉エノキ鍋",
    "Beef Enoki Casserole",
    1000,
    "casserole",
    "casserole_beef_enoki.png",
  ],

  // noodles
  ["麻辣烫", "マーラータン", "Malatang", 900, "noodles", "spicy_malatang.png"],
  [
    "麻辣香锅",
    "マーラージャンゴオ",
    "Spicy Hot Pot",
    1000,
    "noodles",
    "spicy_hot_pot.png",
  ],
  [
    "麻辣米线",
    "マーラー米ヌードル",
    "Spicy Rice Noodles",
    900,
    "noodles",
    "spicy_rice_noodles.png",
  ],
  [
    "麻辣方便面",
    "マーラインスタントラーメン",
    "Spicy Instant Noodles",
    900,
    "noodles",
    "spicy_instant_noodles.png",
  ],
  [
    "麻辣拌面",
    "マーラーまぜ麺",
    "Spicy Mixed Noodles",
    1000,
    "noodles",
    "spicy_mixed_noodles.png",
  ],
  [
    "麻辣乌冬面",
    "マーラーうどん",
    "Spicy Udon Noodles",
    900,
    "noodles",
    "spicy_udon_noodles.png",
  ],
  [
    "土豆粉",
    "ジャガイモ麺",
    "Potato Starch Noodles",
    900,
    "noodles",
    "spicy_potato_starch_noodles.png",
  ],
  [
    "牛筋面",
    "まぜもちもち麺",
    "Chewy Noodles",
    900,
    "noodles",
    "spicy_chewy_noodles.png",
  ],
  [
    "大盘鸡拌面",
    "鶏肉と野菜あんかけ麺",
    "Spicy Chicken with Noodles",
    1000,
    "noodles",
    "spicy_chicken_noodles.png",
  ],
  [
    "酸辣粉",
    "サンラー春雨",
    "Hot and Sour Glass Noodles",
    900,
    "noodles",
    "spicy_hot_sour_glass_noodles.png",
  ],
  [
    "板面",
    "板麺",
    "Sword Shaved Noodles",
    1000,
    "noodles",
    "spicy_sword_shaved_noodles.png",
  ],
  [
    "酸辣小面",
    "重慶サンラー麺",
    "Hot and Sour Noodles",
    1000,
    "noodles",
    "spicy_hot_sour_noodles.png",
  ],
  [
    "麻辣小面",
    "重慶マーラー麺",
    "Mala Noodles",
    1000,
    "noodles",
    "spicy_mala_noodles.png",
  ],
  [
    "卤煮",
    "煮物麺",
    "Braised Pork Offal Stew Noodles",
    1000,
    "noodles",
    "spicy_braised_pork_offal_stew_noodles.png",
  ],
  [
    "牛肉面",
    "牛肉麺",
    "Beef Noodles",
    900,
    "noodles",
    "noodles_beef_noodles.png",
  ],
  [
    "牛肉乌冬",
    "牛肉うどん",
    "Beef Udon",
    900,
    "noodles",
    "noodles_beef_udon.png",
  ],
  [
    "牛肉米线",
    "牛肉米ヌードル",
    "Beef Soup Rice Noodles",
    900,
    "noodles",
    "noodles_beef_soup_rice_noodles.png",
  ],
  [
    "𰻝𰻝面",
    "ビャンビャン麺",
    "Biang Biang Noodles",
    900,
    "noodles",
    "noodles_biang_biang_noodles.png",
  ],
  [
    "鸡汤米线",
    "鶏スープ米ヌードル",
    "Chicken Soup Rice Noodles",
    900,
    "noodles",
    "noodles_chicken_soup_rice_noodles.png",
  ],
  [
    "鸭血粉丝汤",
    "鴨の血と春雨スープ",
    "Duck Blood Vermicelli Soup",
    1000,
    "noodles",
    "noodles_duck_blood_vermicelli_soup.png",
  ],
  ["担担面", "担々麺", "Tantanmen", 1000, "noodles", "noodles_tantanmen.png"],
  [
    "海鲜汤面",
    "海鮮タンメン",
    "Seafood Noodles",
    1000,
    "noodles",
    "noodles_seafood_noodles.png",
  ],
  [
    "鸡肉面",
    "鶏肉麺",
    "Chicken Noodles",
    1000,
    "noodles",
    "noodles_chicken_noodles.png",
  ],
  [
    "肥肠面",
    "豚ホルモン麺",
    "Large Intestine Noodles",
    900,
    "noodles",
    "noodles_large_intestine_noodles.png",
  ],
  [
    "排骨面",
    "パイコウ麺",
    "Pork Ribs Noodles",
    1000,
    "noodles",
    "noodles_pork_ribs_noodles.png",
  ],
  [
    "蔬菜汤面",
    "野菜タンメン",
    "Vegetable Noodle Soup",
    1000,
    "noodles",
    "noodles_vegetable_noodle_soup.png",
  ],
  [
    "豚骨拉面",
    "豚骨ラーメン",
    "Pork Bone Ramen",
    1000,
    "noodles",
    "noodles_pork_bone_ramen.png",
  ],
];

db.serialize(() => {
  db.run("DELETE FROM menu", [], (deleteErr) => {
    if (deleteErr) {
      console.error("删除旧菜单失败:", deleteErr.message);
      process.exit(1);
    }

    const stmt = db.prepare(
      "INSERT INTO menu (name_zh, name_ja, name_en, price, category, image, is_available) VALUES (?, ?, ?, ?, ?, ?, 1)",
    );
    items.forEach((item) => stmt.run(item));
    stmt.finalize((insertErr) => {
      if (insertErr) {
        console.error("导入完整菜单失败:", insertErr.message);
        process.exit(1);
      }
      db.get("SELECT COUNT(*) AS count FROM menu", [], (countErr, row) => {
        if (countErr) {
          console.error("查询菜单数量失败:", countErr.message);
          process.exit(1);
        }
        console.log(`完整菜单导入成功，共 ${row.count} 条`);
        db.close();
      });
    });
  });
});
